# Generated by Django 4.1.2 on 2023-01-27 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0002_movie_actors_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="role_name",
        ),
    ]
