# Generated by Django 4.1.2 on 2023-01-27 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0003_remove_role_role_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="date",
        ),
    ]
