# Generated by Django 4.1.2 on 2023-01-28 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0004_remove_movie_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Role",
        ),
    ]
