# Generated by Django 4.1.2 on 2023-01-30 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actor", "0005_alter_actor_average_movie_rate"),
        ("movie_app", "0005_delete_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(related_name="movies", to="actor.actor"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="rate",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                max_digits=2,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Invalid rate number"
                    ),
                    django.core.validators.MaxValueValidator(
                        10, message="Max value is 10"
                    ),
                    django.core.validators.DecimalValidator(
                        decimal_places=1, max_digits=2
                    ),
                ],
            ),
        ),
    ]
