# Generated by Django 4.1.5 on 2023-01-20 19:43

import actor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=155)),
                ("last_name", models.CharField(max_length=155)),
                ("description", models.TextField(blank=True, null=True)),
                ("average_movie_rate", models.FloatField()),
                ("date_of_birth", models.DateTimeField()),
                (
                    "image",
                    models.ImageField(blank=True, upload_to=actor.models.upload_image),
                ),
            ],
            options={
                "verbose_name": "Actor",
                "verbose_name_plural": "Actors",
            },
        ),
    ]
