# Generated by Django 4.1.5 on 2023-01-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="date_of_birth",
            field=models.DateField(),
        ),
    ]
