# Generated by Django 4.1.2 on 2023-01-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie_app", "0001_initial"),
        ("actor", "0002_alter_actor_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="actor",
            name="role",
            field=models.ManyToManyField(to="movie_app.movie"),
        ),
    ]
