# Generated by Django 4.1.2 on 2023-01-27 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("actor", "0003_actor_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actor",
            name="role",
        ),
    ]
